### PR TITLE
[WIP] Flexible redshift catalog loading

### LINKED ISSUE #9: Allow flexibility in selecting redshift catalogs
In preparation for DR1 patching, load from `SPECPROD/zcatalog/v1/*.fits` instead of `SPECPROD/zcatalog/*.fits` or a VAC patch.

### LINKED ISSUE #10: Move source versions to configuration file
Currently versions of *e.g.* `lsdr9-photometry` are specified as command-line options, with defaults.  A better way to do this might be to have a configuration file embedded in the product with sections for each specprod. For example:
```ini
[fuji]
lsdr9-photometry = v2.1
fiberassign = 0.5

[guadalupe]
lsdr9-photometry = v2.2
fiberassign = 1.0

[iron]
; ...
```

### LINKED ISSUE #11: Prepare DB to load from SPECPROD/zcatalog/v1/*.fits instead of SPECPROD/zcatalog/*.fits + VAC of patches
Depends on #9 & #10.

### PR DESCRIPTION
**Pull request by weaverba137**
**Work In Progress**

This PR:

* Closes #9 
* Closes #10 
* Closes #11

### CODE REVIEW

**Comment by weaverba137** [comment]
Saving some `iron` load timing data for information purposes.

* `exposures`: 00:00:31
* `photometry`: 09:26
* `targetphot`: ~08:45
* `target`: 08:51
* `redshift`: 09:32
* `fiberassign`: 11:41

**Comment by weaverba137** [comment]
@sbailey, here are tests I ran related to missing or added columns:

1. Removed `firstnight`, `lastnight` from `guadalupe_test.zpix`, but retained the column definitions in the SQLAlchemy code (`specprodDB.load.Zpix`).
2. Removed `firstnight`, `lastnight` from the SQLAlchemy code (`specprodDB.load.Zpix`), but retained the columns in `fuji.zpix` (it turns out `guadalupe.zpix` does not have `firstnight`, `lastnight`).

Results:

* In both cases I used the [database tutorial notebook](https://github.com/desihub/tutorials/blob/main/database/spectroscopic-production-database.ipynb).
* In case 1, if I access `specprodDB.load.Zpix` as a whole object (*e.g.* `db.dbSession.query(db.Photometry, db.Zpix).filter(...)`), or if I explicitly try to access `Zpix.firstnight`, `Zpix.lastnight`, an error is thrown: `ProgrammingError: (psycopg2.errors.UndefinedColumn) column zpix.firstnight does not exist`.
* In case 2, I ran through the entire notebook without any errors. The presence of `firstnight`, `lastnight` in the database was simply ignored.  If I try to explicitly access `specprodDB.load.Zpix.firstnight`, I get an `AttributeError`, which is expected.

Conclusions:

* `fuji` can still be accessed with future versions of `specprod-db` that do not have `Zpix.firstnight`, `Zpix.lastnight` defined, as long as user code does not explicitly try to access these columns.
* We should not try to access `guadalupe` and `iron` (specifically `guadalupe.zpix` and `iron.zpix`) with older versions of `specprod-db`.

**Comment by weaverba137** [comment]
@sbailey, I believe this is ready for merge. This will clear several items off of the DR1 and DR1 patching projects.

**Comment by sbailey** [comment]
Thanks.  I'll merge now, but post-facto request: in your comment above, please confirm whether the timing numbers are minutes:seconds or hours:minutes.  If minutes:seconds, it seems surprisingly fast, but if hours:minutes it seems concerningly slow when projecting to future releases, which may require more work to optimize.

**Comment by weaverba137** [comment]
Heh, never thought to add units! Those are all hours:minutes, except for the exposures table stage, and those are in fact very small files.  For completeness, here is the timing for the most recent loads:

### guadalupe

Timing wall-clock time reported by Slurm, in `HH:MM:SS`.

* `exposures`: 00:00:24
* `photometry`: 01:56:43
* `targetphot`: 00:25:52
* `target`: 00:43:13
* `redshift`: 00:35:58
* `fiberassign`: 00:22:22

### iron

* `exposures`: 00:01:09
* `photometry`: 08:48:57
* `targetphot`: 06:11:05
* `target`: 06:35:08
* `redshift`: 05:24:51
* `fiberassign`: 03:36:56

The timing for `iron` actually seems to have improved, possibly because the filesystem was a bit more stable. I also ran a lot of it over the weekend. I have not tried to optimize by using the read-only filesystem, but that's worth exploring.

Finally, I will also create a tag, probably tomorrow morning at this point.

**Pull request merged**
