### PR TITLE
Load healpixel targeting bitmasks and correct them

### LINKED ISSUE #2: Fix the zpix table to include targeting bits in DR1 (and Guadalupe?)
Assuming the zall-pix-{SPECPROD}.fits catalogs are correct in assigning the targeting bits to the healpix coadded spectra, keep the targeting bits in the `zpix` table. The complete list is: ['cmx_target','desi_target','bgs_target','mws_target','sv1_desi_target','sv1_bgs_target','sv1_mws_target','sv2_desi_target','sv2_bgs_target','sv2_mws_target','sv3_desi_target','sv3_bgs_target','sv3_mws_target','scnd_target','sv1_scnd_target','sv2_scnd_target','sv3_scnd_target']

This shall be fixed for DR1 (assuming it is `iron`, and for the following SPECPRODs). It would also be nice for Guadalupe but less crucial as that schema will likely be less commonly used.

### LINKED ISSUE #3: Create short tutorial notebook dealing with edge cases
Separately from the general Database Tutorial Notebook, create a short notebook with more advanced queries that illustrate some documented edge cases such as healpix coadds that have different values of targeting information due to targets being secondary on a tile while only primary on a different tile of the same survey and program. If relevant, include other edge cases that are otherwise difficult to document.

This is anticipated to be insightful for completeness and documentation but likely rarely used and not necessary to most scientific use cases, so it has a lower priority than updating the main [Database Tutorial Notebook](https://github.com/desihub/tutorials/blob/main/database/spectroscopic-production-database.ipynb).

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

* Fixes #2.
* Fixes #3.
* The `zpix` table now includes all targeting bitmasks. These are intended to represent the "best" bitmasks, and may differ in a very small number of cases from the values in the `zall-pix-$SPECPROD.fits` file.
  - The `zpix` table is first loaded "as-is" from the `zall-pix-$SPECPROD.fits` file, and then only those rows (79 rows in `fuji`) that are identified as problematic are updated. All other rows should already be correct (including, by chance, a few of the problematic rows, but updating 79 is better than updating 2 million).
  - Note that the update takes place after the *fiberassign* load because that table is needed to do the identification.
* A notebook documenting the procedure for identifying and fixing certain corner cases is added.
* Updates the Spin implementation of the database for improved memory performance.

Please test by logging in to NERSC and connecting to the database in the usual way.  Then test using the `fuji_test` schema. Spot checks for identical results between `fuji` and `fuji_test` would also be welcome. The plan is that once testing is complete, we can simply replace `fuji` with `fuji_test` just by renaming the schema.

A reload will also be performed on `guadalupe`, but the priority of that may mean that it happens after EDR.

### CODE REVIEW

**Comment by weaverba137** [comment]
@geordie666 reports that there are a small number of additional examples where `sv1_mws_target` exhibits the problematic behavior, even while `sv1_desi_target` remains the same. Incorporate logic to capture that case as well before merging.

**Comment by stephjuneau** [comment]
> @geordie666 reports that there are a small number of additional examples where `sv1_mws_target` exhibits the problematic behavior, even while `sv1_desi_target` remains the same. Incorporate logic to capture that case as well before merging.

To confirm, for both the previously known sv1_desi_target cases and those new sv1_mws_target cases, the updated columns will include updates to sv1_scnd_target, correct? Also, I haven't checked the sv1_bgs_target column but maybe @geordie666 did?

**Comment by weaverba137** [comment]
That is correct, although if there is documentation that indicates otherwise, could you please point it out, or go ahead and fix that?

**Comment by geordie666** [comment]
@stephjuneau: I checked the `SV1_BGS_TARGET` column and there are **_zero_** problematic rows for the BGS. 

The MWS cases are caused by an update to `desitarget` in version `0.48.0` of the code that [reverted WD primary targets to an older selection](https://github.com/desihub/desitarget/blob/0.48.0/doc/changes.rst). The three cases I found all have the `MWS_WD` bit additionally set in the `SV1_MWS_TARGET` column. So, this is an issue from the same era as the other SV1 cases we already identified.

Oh, and in the three`SV1_MWS_TARGET` cases I identified, there **_are no updates to the_** `SV1_SCND_TARGET` column. Only the (primary) `MWS_WD` bit was changed.

**Comment by stephjuneau** [comment]
Hi @weaverba137, I see some commits coming in. Would you mind to tag me in a comment when this is ready for a review? Namely, I prepared a test query to check on the new sv1_desi_target and sv1_scnd_target values. I can add a check for the sv1_mws_target values. Also, if you plan on fixing sv3_desi_target for sv3-bright in the same PR (or maybe you already have), I could add another check for this as well. Thank you!

**Comment by weaverba137** [comment]
@stephjuneau, please go ahead with your testing. The table `fuji_test.zpix` has now been updated to address all three of these anomalies:
* differing values of `sv1_desi_target`.
* differing values of `sv1_mws_target`.
* Zeroed-out targeting bits for ToO observations in sv3 (both bright and dark).

**Comment by stephjuneau** [comment]
> @stephjuneau, please go ahead with your testing. The table `fuji_test.zpix` has now been updated to address all three of these anomalies:
> 
> * differing values of `sv1_desi_target`.
> * differing values of `sv1_mws_target`.
> * Zeroed-out targeting bits for ToO observations in sv3 (both bright and dark).

Hi @weaverba137 , could you tell me where the targeting bits for the ToO were obtained from? (for making an independent comparison of values).

**Comment by weaverba137** [comment]
Those are also in the `target` table, ultimately from `lsdr9-photometry`. See also the example notebook in this PR.

**Comment by stephjuneau** [comment]
Separate question for @weaverba137: would adding RA, DEC, REF_EPOCH coordinate columns also be done in this PR on `fuji_test.zpix` ? If so, I would be happy to extend my review to check on those.

**Comment by weaverba137** [comment]
That is beyond the scope of this PR.  It would not only require a separate PR, but a separate reload of the database.

**Comment by stephjuneau** [comment]
Hi @weaverba137, one of my tests was to run the query with BIT_OR on all 17 targeting columns and compare the new table with the original zpix file to see how many rows have different values. Relative to what you reported above, I found the following: 
- 230 rows in 'sv3' (bright and dark) with new values of SV3_DESI_TARGET and SV3_SCND_TARGET (which are the ToO)
- 42 rows in 'sv1' (dark) including 39 secondary and 3 MWS-only cases (reported before)
- 185 rows in 'cmx' (other) which I don't think were reported before (@geordie666 ?)

Here are some example TARGETIDs for which I find new values of CMX_TARGET when joining zpix with both target and fiberassign tables and grouping with BIT_OR: `TARGETID_CMX = [39628473198711006, 39628473207097483, 39628540454374918]`

Would you like to also fix the CMX_TARGET column as part of this same PR?

**Comment by geordie666** [comment]
I didn't check `cmx` (and never do, generally). But, yes, it's entirely possible that all sorts of strange occurrences happened during commissioning, when we weren't striving for reproducibility.

@stephjuneau: Let me know if you want me to explicitly check your working for `cmx` cases or whether you were just asking for an opinion as to whether strange cases might be expected in `cmx`.

Personally, I'd be tempted to always include a disclaimer for any published data from `cmx` stating that commissioning was a developmental phase and issues with reproducibility should be anticipated.

**Comment by stephjuneau** [comment]
> I didn't check `cmx` (and never do, generally). But, yes, it's entirely possible that all sorts of strange occurrences happened during commissioning, when we weren't striving for reproducibility.
> 
> @stephjuneau: Let me know if you want me to explicitly check your working for `cmx` cases or whether you were just asking for an opinion as to whether strange cases might be expected in `cmx`.
> 
> Personally, I'd be tempted to always include a disclaimer for any published data from `cmx` stating that commissioning was a developmental phase and issues with reproducibility should be anticipated.

So it seems that the CMX case is that sometimes the DESI_TARGET column is set to zero and sometimes it's not but for the same value of CMX_TARGET. Not sure which of the two is the preferred scenario?

**Comment by geordie666** [comment]
`CMX_TARGET` is meant to mean `DESI_TARGET` but just for the `cmx` phase of DESI. So, I'd say `DESI_TARGET==0` is _always_ correct for `cmx`. But, there could be reasons that this principle was altered downstream of the `desitarget` code that I don't remember (or know, or understand).

I think we can make any choices we like for `cmx`! So, I'd vote for always setting `DESI_TARGET==0` in the database if `CMX_TARGET !=0`.

**Comment by stephjuneau** [comment]
Closing up on the CMX case: the database `target` tables indeed has DESI_TARGET==0 for the 'cmx' survey. It's the zall-pix-fuji.fits file that had non-zero values for 185 out of 4146 CMX targets for some reason. So I'll go ahead and assume that DESI_TARGET=0 is correct, which means that @weaverba137 doesn't need to change anything on the database side for this case! (However, I'll fix them in the EDR zpix VAC for consistency with the database).

**Comment by weaverba137** [comment]
Does that mean that all testing on *this PR* is done?

**Comment by stephjuneau** [comment]
> Does that mean that all testing on _this PR_ is done?

Almost! I just need to confirm my suspicion that the difference between the "79 rows" that you quoted (and that I recover by running the query at NERSC) and the "42 rows in SV1" is indeed because 79-42 = 37 were correct by chance. Everything else is looking good so far.

**Comment by weaverba137** [comment]
The most recent push implements the suggestions in @sbailey email desi-data 6350.  For the record, the commands below will get the `fuji_test2` schema in sync with the code as of ff1346a.
```sql
ALTER TABLE fuji_test2.zpix DROP COLUMN mean_fiber_ra;
ALTER TABLE fuji_test2.zpix DROP COLUMN mean_fiber_dec;
ALTER TABLE fuji_test2.zpix DROP COLUMN std_fiber_ra;
ALTER TABLE fuji_test2.zpix DROP COLUMN std_fiber_dec;
ALTER TABLE fuji_test2.zpix DROP COLUMN mean_delta_x;
ALTER TABLE fuji_test2.zpix DROP COLUMN mean_delta_y;
ALTER TABLE fuji_test2.zpix DROP COLUMN rms_delta_x;
ALTER TABLE fuji_test2.zpix DROP COLUMN rms_delta_y;
ALTER TABLE fuji_test2.zpix DROP COLUMN mean_psf_to_fiber_specflux;
ALTER TABLE fuji_test2.ztile DROP COLUMN mean_fiber_ra;
ALTER TABLE fuji_test2.ztile DROP COLUMN mean_fiber_dec;
ALTER TABLE fuji_test2.ztile DROP COLUMN std_fiber_ra;
ALTER TABLE fuji_test2.ztile DROP COLUMN std_fiber_dec;
ALTER TABLE fuji_test2.ztile DROP COLUMN mean_delta_x;
ALTER TABLE fuji_test2.ztile DROP COLUMN mean_delta_y;
ALTER TABLE fuji_test2.ztile DROP COLUMN rms_delta_x;
ALTER TABLE fuji_test2.ztile DROP COLUMN rms_delta_y;
ALTER TABLE fuji_test2.ztile DROP COLUMN mean_psf_to_fiber_specflux;
ALTER TABLE fuji_test2.fiberassign DROP COLUMN plate_ra;
ALTER TABLE fuji_test2.fiberassign DROP COLUMN plate_dec;
ALTER TABLE fuji_test2.fiberassign ADD COLUMN pmra REAL NOT NULL;
ALTER TABLE fuji_test2.fiberassign ADD COLUMN pmdec REAL NOT NULL;
ALTER TABLE fuji_test2.fiberassign ADD COLUMN ref_epoch REAL NOT NULL;
ALTER TABLE fuji_test2.fiberassign ADD COLUMN parallax REAL NOT NULL;
ALTER TABLE fuji_test2.fiberassign ADD COLUMN subpriority DOUBLE PRECISION NOT NULL;
```

**Comment by sbailey** [comment]
>> Ben: Does that mean that all testing on this PR is done?

> Stephanie: Almost! I just need to confirm my suspicion that the difference between the "79 rows" that you quoted (and that I recover by running the query at NERSC) and the "42 rows in SV1" is indeed because 79-42 = 37 were correct by chance. Everything else is looking good so far.

@stephjuneau are you ready to sign off on this PR or are there still checks you'd like to do?

**Comment by stephjuneau** [comment]
I can redo the tests on the next version of fuji_test. In particular, the changes are mostly applied to the targeting columns added to zpix. In fact, those are already correct in the VAC so in terms of efficiency and use of everyone's time and effort, I will redo the tests on the zpix based on the VAC. If all the tests pass, we can repeat for ztile. That said, the ztile doesn't need to extra targeting columns because it includes TILEID which breaks the degeneracy when joining with target.

**Comment by weaverba137** [comment]
The most recent database load completed last night and is now the new `fuji_test`.

**Pull request merged**
